version: "3"

services:
  mysql:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: localdb
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_USER: localuser
      MYSQL_PASSWORD: Passw0rd
      TZ: Asia/Tokyo
  #   image: mysql:5.7.34
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: testuser
  #     MYSQL_PASSWORD: testpass
  #     TZ: Asia/Tokyo
  #   ports:
  #       - 3306:3306
  #   build:
  #     context: ./docker/mysql
  #     dockerfile: Dockerfile
  #   volumes:
  #       - ./:/usr/src/app/mysql
  #       - .docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
  front:
    build:
      context: ./docker/front
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/front
    command: sh -c "cd front && npm install && npm run dev"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
  server:
    build:
      context: ./docker/server
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/server
    # volumes:
    #   - type: bind
    #     source: .
    #     target: ./docker/server/usr/src/app/server
    command: sh -c "cd server && npm ci && npm run start:dev"
    tty: true
    ports:
      - "4000:4000"